import type { Resource } from "@/types";

/**
 * Curated database of high-quality learning resources.
 * Each resource is hand-verified for quality, relevance, and effectiveness.
 * No random or unverified resources are included.
 */

export const CURATED_RESOURCES: Resource[] = [
  // ==================== Web Development - Frontend ====================

  {
    id: "res_mdn_html",
    title: "MDN Web Docs - HTML",
    type: "documentation",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    description: "Official Mozilla documentation for HTML. Comprehensive, accurate, and regularly updated.",
    cost: "free",
    careerPaths: ["frontend", "fullstack"],
    skillLevels: ["beginner", "intermediate"],
    roadmapStages: ["beginner", "intermediate"],
    topics: ["HTML", "Web Basics"],
    rating: 5,
    reviewed: true,
    tags: ["official", "comprehensive", "must-read"],
    language: "en",
  },
  {
    id: "res_mdn_css",
    title: "MDN Web Docs - CSS",
    type: "documentation",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    description: "Official Mozilla CSS documentation. The gold standard for CSS learning.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "ui-ux"],
    skillLevels: ["beginner", "intermediate", "advanced"],
    roadmapStages: ["beginner", "intermediate", "advanced"],
    topics: ["CSS", "Styling", "Layout"],
    rating: 5,
    reviewed: true,
    tags: ["official", "reference", "essential"],
    language: "en",
  },
  {
    id: "res_mdn_js",
    title: "MDN Web Docs - JavaScript",
    type: "documentation",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    description: "Official JavaScript documentation. Essential reference for any JS developer.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["beginner", "intermediate", "advanced"],
    roadmapStages: ["beginner", "intermediate", "advanced"],
    topics: ["JavaScript", "ES6", "Async", "DOM"],
    rating: 5,
    reviewed: true,
    tags: ["official", "reference", "critical"],
    language: "en",
  },
  {
    id: "res_react_official",
    title: "React Official Documentation",
    type: "documentation",
    url: "https://react.dev",
    description: "Official React documentation with interactive tutorials and examples.",
    cost: "free",
    careerPaths: ["frontend", "fullstack"],
    skillLevels: ["beginner", "intermediate", "advanced"],
    roadmapStages: ["intermediate", "advanced"],
    topics: ["React", "Components", "Hooks", "State"],
    rating: 5,
    reviewed: true,
    tags: ["official", "interactive", "up-to-date"],
    language: "en",
  },
  {
    id: "res_fcc_responsive_design",
    title: "FreeCodeCamp - Responsive Web Design",
    type: "course",
    url: "https://www.freecodecamp.org/learn/responsive-web-design/",
    description: "Free comprehensive course covering HTML, CSS, and responsive design. Hands-on projects included.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "ui-ux"],
    skillLevels: ["beginner"],
    roadmapStages: ["beginner"],
    topics: ["HTML", "CSS", "Responsive Design", "Projects"],
    rating: 5,
    reviewed: true,
    tags: ["free", "hands-on", "project-based"],
    language: "en",
  },
  {
    id: "res_fcc_javascript",
    title: "FreeCodeCamp - JavaScript Algorithms and Data Structures",
    type: "course",
    url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
    description: "Comprehensive JavaScript course from basics to advanced concepts and DSA.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["beginner", "intermediate"],
    roadmapStages: ["beginner", "intermediate"],
    topics: ["JavaScript", "DSA", "Algorithms"],
    rating: 5,
    reviewed: true,
    tags: ["free", "comprehensive", "dsa"],
    language: "en",
  },
  {
    id: "res_scrimba_react",
    title: "Scrimba - Learn React",
    type: "course",
    url: "https://scrimba.com/learn/react",
    description: "Interactive React course with video tutorials and coding exercises. Very engaging format.",
    cost: "freemium",
    careerPaths: ["frontend", "fullstack"],
    skillLevels: ["beginner", "intermediate"],
    roadmapStages: ["intermediate"],
    topics: ["React", "Components", "Hooks"],
    rating: 5,
    reviewed: true,
    tags: ["interactive", "video", "hands-on"],
    language: "en",
  },
  {
    id: "res_leetcode",
    title: "LeetCode",
    type: "practice",
    url: "https://leetcode.com",
    description: "Premier platform for coding problems and interview preparation. Used by top companies.",
    cost: "freemium",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["intermediate", "advanced"],
    roadmapStages: ["intermediate", "advanced"],
    topics: ["Algorithms", "Data Structures", "Interview Prep"],
    rating: 5,
    reviewed: true,
    tags: ["practice", "interview-prep", "competitive"],
    language: "en",
  },
  {
    id: "res_codewars",
    title: "Codewars",
    type: "practice",
    url: "https://www.codewars.com",
    description: "Gamified coding practice platform. Great for improving problem-solving skills.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["beginner", "intermediate", "advanced"],
    roadmapStages: ["beginner", "intermediate", "advanced"],
    topics: ["Multiple Languages", "Problem Solving", "Algorithms"],
    rating: 4.5,
    reviewed: true,
    tags: ["gamified", "free", "fun"],
    language: "en",
  },

  // ==================== Backend & Full Stack ====================

  {
    id: "res_nodejs_docs",
    title: "Node.js Official Documentation",
    type: "documentation",
    url: "https://nodejs.org/docs",
    description: "Official Node.js documentation. Essential for backend JavaScript development.",
    cost: "free",
    careerPaths: ["backend", "fullstack"],
    skillLevels: ["beginner", "intermediate", "advanced"],
    roadmapStages: ["beginner", "intermediate", "advanced"],
    topics: ["Node.js", "Server", "Async", "APIs"],
    rating: 5,
    reviewed: true,
    tags: ["official", "reference", "critical"],
    language: "en",
  },
  {
    id: "res_postgresql_docs",
    title: "PostgreSQL Official Documentation",
    type: "documentation",
    url: "https://www.postgresql.org/docs/",
    description: "Complete PostgreSQL documentation. Industry-standard relational database.",
    cost: "free",
    careerPaths: ["backend", "fullstack", "data-science"],
    skillLevels: ["beginner", "intermediate", "advanced"],
    roadmapStages: ["intermediate", "advanced"],
    topics: ["PostgreSQL", "SQL", "Databases"],
    rating: 5,
    reviewed: true,
    tags: ["official", "database", "essential"],
    language: "en",
  },
  {
    id: "res_nextjs_docs",
    title: "Next.js Official Documentation",
    type: "documentation",
    url: "https://nextjs.org/docs",
    description: "Official Next.js documentation. Modern fullstack React framework.",
    cost: "free",
    careerPaths: ["frontend", "fullstack"],
    skillLevels: ["intermediate", "advanced"],
    roadmapStages: ["intermediate", "advanced"],
    topics: ["Next.js", "React", "Fullstack", "API Routes"],
    rating: 5,
    reviewed: true,
    tags: ["official", "modern", "fullstack"],
    language: "en",
  },
  {
    id: "res_mongodb_university",
    title: "MongoDB University",
    type: "course",
    url: "https://learn.mongodb.com",
    description: "Free official courses on MongoDB. Official source for MongoDB learning.",
    cost: "free",
    careerPaths: ["backend", "fullstack"],
    skillLevels: ["beginner", "intermediate"],
    roadmapStages: ["intermediate"],
    topics: ["MongoDB", "NoSQL", "Databases"],
    rating: 4.5,
    reviewed: true,
    tags: ["official", "free", "database"],
    language: "en",
  },

  // ==================== YouTube Channels ====================

  {
    id: "res_yt_traversymedia",
    title: "YouTube - Traversy Media",
    type: "youtube",
    url: "https://www.youtube.com/channel/UC29ju8bIPH5as8OGnQzwJQw",
    description: "Best web development tutorials on YouTube. Covers frontend, backend, and fullstack.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["beginner", "intermediate"],
    roadmapStages: ["beginner", "intermediate"],
    topics: ["Web Development", "Multiple Frameworks", "Best Practices"],
    rating: 5,
    reviewed: true,
    tags: ["youtube", "tutorial", "popular"],
    language: "en",
  },
  {
    id: "res_yt_fireship",
    title: "YouTube - Fireship",
    type: "youtube",
    url: "https://www.youtube.com/c/Fireship",
    description: "High-quality, concise technical explainers. Perfect for quick learning.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["beginner", "intermediate", "advanced"],
    roadmapStages: ["beginner", "intermediate", "advanced"],
    topics: ["Web Dev", "Cloud", "Tools", "Concepts"],
    rating: 5,
    reviewed: true,
    tags: ["youtube", "concise", "quality"],
    language: "en",
  },
  {
    id: "res_yt_codesandbox",
    title: "YouTube - Web Dev Simplified",
    type: "youtube",
    url: "https://www.youtube.com/c/WebDevSimplified",
    description: "Simplified explanations of complex web development concepts.",
    cost: "free",
    careerPaths: ["frontend", "fullstack"],
    skillLevels: ["beginner", "intermediate"],
    roadmapStages: ["beginner", "intermediate"],
    topics: ["React", "JavaScript", "Web Dev", "CSS"],
    rating: 5,
    reviewed: true,
    tags: ["youtube", "educational", "popular"],
    language: "en",
  },

  // ==================== GitHub Repositories ====================

  {
    id: "res_github_awesome_webdev",
    title: "GitHub - Awesome Web Development",
    type: "github",
    url: "https://github.com/topics/awesome",
    description: "Curated lists of awesome resources organized by topic. Great reference.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["beginner", "intermediate", "advanced"],
    roadmapStages: ["beginner", "intermediate", "advanced"],
    topics: ["Resources", "Reference", "Collections"],
    rating: 4.5,
    reviewed: true,
    tags: ["github", "curated", "reference"],
    language: "en",
  },
  {
    id: "res_github_javascript_algorithms",
    title: "GitHub - JavaScript Algorithms and Data Structures",
    type: "github",
    url: "https://github.com/trekhleb/javascript-algorithms",
    description: "JavaScript implementations of classic algorithms and data structures with explanations.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["intermediate", "advanced"],
    roadmapStages: ["intermediate", "advanced"],
    topics: ["Algorithms", "Data Structures", "Interview Prep"],
    rating: 5,
    reviewed: true,
    tags: ["github", "educational", "algorithms"],
    language: "en",
  },
  {
    id: "res_github_freeCodeCamp",
    title: "GitHub - FreeCodeCamp Open Source",
    type: "github",
    url: "https://github.com/freeCodeCamp/freeCodeCamp",
    description: "Open source learning platform. Great for contributing while learning.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["intermediate", "advanced"],
    roadmapStages: ["intermediate", "advanced"],
    topics: ["Open Source", "Web Dev", "Contributing"],
    rating: 5,
    reviewed: true,
    tags: ["github", "open-source", "learning"],
    language: "en",
  },

  // ==================== Books ====================

  {
    id: "res_book_eloquent_js",
    title: "Eloquent JavaScript (Free Online)",
    type: "book",
    url: "https://eloquentjavascript.net",
    description: "Excellent free online book. Comprehensive JavaScript education from basics to advanced.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["beginner", "intermediate"],
    roadmapStages: ["beginner", "intermediate"],
    topics: ["JavaScript", "Fundamentals", "Programming"],
    rating: 5,
    reviewed: true,
    tags: ["free", "comprehensive", "classic"],
    language: "en",
  },
  {
    id: "res_book_you_dont_know_js",
    title: "You Don't Know JS Yet",
    type: "book",
    url: "https://github.com/getify/You-Dont-Know-JS",
    description: "Deep dive into JavaScript mechanics. Free online. Essential for intermediate developers.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["intermediate", "advanced"],
    roadmapStages: ["intermediate", "advanced"],
    topics: ["JavaScript", "Deep Learning", "Advanced"],
    rating: 5,
    reviewed: true,
    tags: ["free", "advanced", "critical"],
    language: "en",
  },
  {
    id: "res_book_clean_code",
    title: "Clean Code by Robert C. Martin",
    type: "book",
    url: "https://www.oreilly.com/library/view/clean-code-a/9780136083238/",
    description: "Industry standard for writing maintainable code. Essential for senior development.",
    cost: "paid",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["intermediate", "advanced"],
    roadmapStages: ["advanced"],
    topics: ["Code Quality", "Best Practices", "Professional"],
    rating: 5,
    reviewed: true,
    tags: ["paid", "professional", "classic"],
    language: "en",
  },

  // ==================== Practice & Interactive ====================

  {
    id: "res_frontendmentor",
    title: "Frontend Mentor",
    type: "practice",
    url: "https://www.frontendmentor.io",
    description: "Real-world frontend challenges with design files. Build portfolio while learning.",
    cost: "freemium",
    careerPaths: ["frontend", "fullstack", "ui-ux"],
    skillLevels: ["beginner", "intermediate"],
    roadmapStages: ["beginner", "intermediate"],
    topics: ["Frontend", "Design to Code", "Portfolio"],
    rating: 5,
    reviewed: true,
    tags: ["portfolio", "practice", "design"],
    language: "en",
  },
  {
    id: "res_hackerrank",
    title: "HackerRank",
    type: "practice",
    url: "https://www.hackerrank.com",
    description: "Coding challenges and interview prep. Corporate-trusted platform.",
    cost: "free",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["beginner", "intermediate", "advanced"],
    roadmapStages: ["beginner", "intermediate", "advanced"],
    topics: ["Algorithms", "Interview Prep", "Coding"],
    rating: 4.5,
    reviewed: true,
    tags: ["practice", "interview", "algorithms"],
    language: "en",
  },
  {
    id: "res_edabit",
    title: "Edabit",
    type: "practice",
    url: "https://edabit.com",
    description: "Fun, bite-sized coding challenges. Great for skill building and learning multiple languages.",
    cost: "freemium",
    careerPaths: ["frontend", "fullstack", "backend"],
    skillLevels: ["beginner", "intermediate"],
    roadmapStages: ["beginner", "intermediate"],
    topics: ["Coding", "Logic", "Multiple Languages"],
    rating: 4.5,
    reviewed: true,
    tags: ["practice", "fun", "bite-sized"],
    language: "en",
  },
];

/**
 * Get resources curated for a specific topic, filtered by career goal, skill level, and roadmap stage.
 * Only returns verified, high-quality resources matching the criteria.
 */
export function getRecommendedResources(
  topic: string,
  careerGoal: string,
  skillLevel: string,
  roadmapStage: string
): Resource[] {
  return CURATED_RESOURCES.filter(
    (resource) =>
      // Must be reviewed for quality
      resource.reviewed &&
      // Must match career path
      resource.careerPaths.includes(careerGoal as any) &&
      // Must match skill level
      resource.skillLevels.includes(skillLevel as any) &&
      // Must match roadmap stage
      resource.roadmapStages.includes(roadmapStage as any) &&
      // Must be relevant to topic (fuzzy match on topics and tags)
      (resource.topics.some((t) =>
        t.toLowerCase().includes(topic.toLowerCase())
      ) ||
        resource.tags.some((tag) =>
          topic.toLowerCase().includes(tag.toLowerCase())
        ))
  ).sort((a, b) => {
    // Sort by rating (highest first), then free resources first
    if (b.rating !== a.rating) return b.rating - a.rating;
    return a.cost === "free" ? -1 : b.cost === "free" ? 1 : 0;
  });
}
